/**
   @file style.c
   @author Jake Donovan (jmpatte8)
   This program is a badly styled program that is responsible for printing 
   a random sequence of characters which should make a paragraph when running the    
   program
*/

#include <stdio.h>
#include <stdlib.h>

/** The maximum amount of characters that can be on a line for this program */
#define MAX_CHAR_LENGTH 72
/** Used when we are generating a random word length so we don't have a word length that is less than 72 when adding
    spaces and adjusting a line's position (this is what I got from reading the code, and this is also the number of
    lines we want in our paragraph
*/
#define TEN 10
/** ASCII code starting point for lowercase letters, this is 'a' */
#define START_OF_ALPHABET 97
/** There are 26 letters in the alphabet when we take the remainder of this we can determine which character we have from the alphabet */
#define ALPHABET 26

/**
   This function is responsible for printing a word using x which is a random word length
   which will then be used by this funciton to generate a random sequence of characters
   of length x which will then be printed by this method
   @param x the length of the word that will be randomly generated
*/
void printWord( int x )
{
     for ( int i = 0; i < x; i++ ) {
         // Print a random lower-case letter.
         printf( "%c", START_OF_ALPHABET + rand() % ALPHABET );
     }
}

/**
   This function is responsible for printing a line that is comprised of a sequence of
   words generated by printWord and returned and added to each printed line. When
   generating each line, each line can contain a sequence of spaces including each word
   this function will print word lengths up to 72 characters which includes spaces as
   well
   @return number of lines
*/
int printLine() 
{
    int count = 0, pos = 0, space = 0;
     
    int len = 1 + rand() % TEN;
     
    // Print a line of words up to a limited length.
    while ( pos + len + space < MAX_CHAR_LENGTH ) {
          if ( space > 0 ) {
              printf( " " );
          }
		
          printWord( len );
          pos += len + space;
          len = 1 + rand() % TEN;
          space = 1;
          count += 1;
    }
   
	  printf( "\n" );
	  return count;
}
 
/**
   Generates a paragraph with a length n, which indicates the number of lines that the
   paragraph will contain and then passes to printLine() to help generate each line
   @param n the number of lines that paragraph will contain
   @return the total number of words that is contained within the paragraph
*/
int printParagraph( int n )
{
    int total = 0;
     
    for ( int i = 0; i < n; i++ ) {
        total += printLine();
    }
     
    return total;
}
 
/**
   Program starting point, generate a paragraph with a specified number of lines w to
   hold in the paragraph and print the number of words within the paragraph
   @return program exit status
*/
int main()
{
    // Print a paragraph with ten lines
    int w = printParagraph( TEN );
    // Print the number of words in the paragraph
    printf( "Words: %d\n", w );
    // Exit successfully
    return EXIT_SUCCESS;
}